### ISSUE TITLE
Add support for @slack/bolt 5.x

### ISSUE THREAD

**Issue by codybrom** [vercel-labs/slack-bolt#214]
Hi Vercel team! 

We're currently running `@vercel/slack-bolt@1.6.5` on Node 24 with Next.js App Router on Vercel in a few different projects and have been wondering when `@vercel/slack-bolt` might add support for the latest major branch of [@slack/bolt](https://github.com/slackapi/bolt-js). 

[Bolt for JavaScript v5.0.0](https://github.com/slackapi/bolt-js/releases/tag/v5.0.0) shipped 8 weeks ago, and [5.1.0](https://github.com/slackapi/bolt-js/releases/tag/v5.1.0) has been available for about a week. The newest version that `@vercel/slack-bolt` allows is 4.7.3, which came out May 27, and Slack hasn't put out any more 4.x releases since. I was curious if 5.x support is on the roadmap, and if there was anything keeping the range where it is that I'm not seeing?

---

Before filing this I figured I should go find out what, if anything, might actually be breaking for this package. I installed 1.6.5 against 5.1.0 and didn't find any noticeable issues.

The receiver only touches three Bolt symbols at runtime (`verifySlackRequest`, `ReceiverAuthenticityError` and `ReceiverMultipleAckError`). All three are unchanged in 5.x. Typecheck also came back clean with `strict` on and `skipLibCheck` off. And running a real HMAC-signed request through `createHandler` behaved identically on both versions: 200 for a valid signature, 401 for an invalid one, challenge echoed on `url_verification` and the event delivered to the listener.

So then I assumed the blocker might be the pinned version on `@slack/oauth@3.0.5` because a comment in `dist/index.js` warned that the adapters target InstallProvider internals. As far as I could tell, that still holds up on `@slack/oauth@4.0.0`. Both `handleInstallPath` and `handleCallback` accept the same arguments and the intercepted response methods are all called the same way in both versions. Most of what actually changed in `install-provider.js` between 3.0.5 and 4.0.0 is just class fields being emitted differently.

I've held off on installing `@slack/bolt` 5.x using `--legacy-peer-deps` because it leaves you with a broken install. `@slack/socket-mode@3.0.1` lists `undici` as a peer and `--legacy-peer-deps` skips peers, so `require('@slack/bolt')` just dies with `Cannot find module 'undici'`.

If it's really just the peer range and the oauth bump, I'm happy to open a PR.

**Comment by malewis5** [comment]
Hey @codybrom, thinking through how to unblock 5.0.0 fastest. Wdyt of `"peerDependencies": { "@slack/bolt": "^4.4.0 || ^5.0.0" }`?

We'd keep @slack/oauth pinned at 3.0.5 for now, but work on supporting that change to 4.0.0 as well.

**Comment by codybrom** [comment]
> Hey [@codybrom](https://github.com/codybrom), thinking through how to unblock 5.0.0 fastest. Wdyt of `"peerDependencies": { "@slack/bolt": "^4.4.0 || ^5.0.0" }`?

That works. I’d drafted, but not yet submitted a PR (#216) to do exactly that and I just pushed it. Seemed like a good idea to add 5.x validation to the CI.

**Comment by malewis5** [comment]
@codybrom Merged #216 and some docs in #218. Going to publish a canary for it shortly.

**Comment by malewis5** [comment]
@codybrom 1.7.0-canary published with this change. https://www.npmjs.com/package/@vercel/slack-bolt/v/1.7.0-canary.20260915001935.ccaf493.

Will follow up with a full release soon.
